from utilidades import ContenidoPedidos, Locales, Pedidos, Pizzas


resultado_consulta_anidada_0 = [Pizzas(nombre='Hawaiiana_S', ingredientes='jamón;piña;queso;salsa de tomate', precio=7379), Pizzas(nombre='Hawaiiana_M', ingredientes='jamón;piña;queso;salsa de tomate', precio=10681), Pizzas(nombre='Hawaiiana_L', ingredientes='jamón;piña;queso;salsa de tomate', precio=17182)]
resultado_consulta_anidada_1 = [Pizzas(nombre='Hawaiiana_S', ingredientes='jamón;piña;queso;salsa de tomate', precio=7379), Pizzas(nombre='Vegetariana_S', ingredientes='champiñones;pimiento;choclo;albahaca;salsa de tomate', precio=9118)]
resultado_consulta_anidada_2 = 8210
resultado_consulta_anidada_3 = [Pizzas(nombre='Tocino BBQ_S', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=7957), Pizzas(nombre='Tocino BBQ_M', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=10344), Pizzas(nombre='Tocino BBQ_L', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=17731), Pizzas(nombre='Camarones sobre ajo_S', ingredientes='camarones;queso;salsa de ajo', precio=8552), Pizzas(nombre='Camarones sobre ajo_M', ingredientes='camarones;queso;salsa de ajo', precio=13193), Pizzas(nombre='Camarones sobre ajo_L', ingredientes='camarones;queso;salsa de ajo', precio=15969), Pizzas(nombre='Tocino BBQ_S', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=7957), Pizzas(nombre='Tocino BBQ_M', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=10344), Pizzas(nombre='Tocino BBQ_L', ingredientes='tocino;salchicha;queso;salsa BBQ', precio=17731)]
resultado_consulta_anidada_4 = 231466
resultado_consulta_anidada_5 = 1940
resultado_consulta_anidada_6 = [Pizzas(nombre='Sublime Sublime Salado con Magia_S', ingredientes='Albahaca;tocino;Salsa Blanca;palta;carne molida;salsa de pimentón', precio=7998), Pizzas(nombre='Encantador Fresquito Tierno con Sazón_S', ingredientes='palta;Lengua de Vampiro;Salsa de Queso;salsa blanca', precio=9615), Pizzas(nombre='Magnífico Radiante Magnífico con Virtud_S', ingredientes='palta;cebolla;albahaca;salsa BBQ', precio=9533)]
resultado_consulta_anidada_7 = [Pizzas(nombre='Increíble Dorado Tentador con Cautela_S', ingredientes='Riñones Asados;Ojos de Gnomo;camarones;carne molida;salsa de ají', precio=9211), Pizzas(nombre='Increíble Dorado Tentador con Cautela_M', ingredientes='Riñones Asados;Ojos de Gnomo;camarones;carne molida;salsa de ají', precio=12350), Pizzas(nombre='Increíble Dorado Tentador con Cautela_L', ingredientes='Riñones Asados;Ojos de Gnomo;camarones;carne molida;salsa de ají', precio=19946), Pizzas(nombre='Asombroso Salado Sabroso con Cariño_S', ingredientes='Piel Marchita;jamón;salsa de pimienta', precio=7933), Pizzas(nombre='Asombroso Salado Sabroso con Cariño_M', ingredientes='Piel Marchita;jamón;salsa de pimienta', precio=11612), Pizzas(nombre='Asombroso Salado Sabroso con Cariño_L', ingredientes='Piel Marchita;jamón;salsa de pimienta', precio=14757), Pizzas(nombre='Fresquito Sabroso Fresquito con Amor_S', ingredientes='Larvas Crujientes;queso;albahaca;Moco de Momia;Baba de Zombie;salsa blanca', precio=7854), Pizzas(nombre='Fresquito Sabroso Fresquito con Amor_M', ingredientes='Larvas Crujientes;queso;albahaca;Moco de Momia;Baba de Zombie;salsa blanca', precio=13962), Pizzas(nombre='Fresquito Sabroso Fresquito con Amor_L', ingredientes='Larvas Crujientes;queso;albahaca;Moco de Momia;Baba de Zombie;salsa blanca', precio=16858)]