from utilidades import ContenidoPedidos


PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_S_1 = [
    ContenidoPedidos(id_pedido=2, nombre='Hawaiiana_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=3, nombre='Hawaiiana_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=3, nombre='Hawaiiana_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=4, nombre='Hawaiiana_M', cantidad=4, descuento=0.37),
	ContenidoPedidos(id_pedido=6, nombre='Hawaiiana_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=7, nombre='Hawaiiana_S', cantidad=1, descuento=0.36),
	ContenidoPedidos(id_pedido=8, nombre='Hawaiiana_L', cantidad=3, descuento=0.3),
	ContenidoPedidos(id_pedido=10, nombre='Hawaiiana_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=13, nombre='Hawaiiana_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=15, nombre='Hawaiiana_M', cantidad=1, descuento=0.34),
	ContenidoPedidos(id_pedido=19, nombre='Hawaiiana_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=20, nombre='Hawaiiana_S', cantidad=3, descuento=0.32),
	ContenidoPedidos(id_pedido=31, nombre='Hawaiiana_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=36, nombre='Hawaiiana_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=37, nombre='Hawaiiana_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=43, nombre='Hawaiiana_L', cantidad=4, descuento=0.15),
	ContenidoPedidos(id_pedido=49, nombre='Hawaiiana_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=54, nombre='Hawaiiana_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=55, nombre='Hawaiiana_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=63, nombre='Hawaiiana_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=63, nombre='Hawaiiana_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=66, nombre='Hawaiiana_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=68, nombre='Hawaiiana_M', cantidad=4, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_S_2 = [
    ContenidoPedidos(id_pedido=2, nombre='Pepperoni Clásica_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=2, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=5, nombre='Pepperoni Clásica_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=8, nombre='Pepperoni Clásica_M', cantidad=4, descuento=0.3),
	ContenidoPedidos(id_pedido=8, nombre='Pepperoni Clásica_M', cantidad=3, descuento=0.3),
	ContenidoPedidos(id_pedido=8, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.3),
	ContenidoPedidos(id_pedido=11, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=12, nombre='Pepperoni Clásica_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=14, nombre='Pepperoni Clásica_M', cantidad=4, descuento=0.28),
	ContenidoPedidos(id_pedido=15, nombre='Pepperoni Clásica_S', cantidad=2, descuento=0.34),
	ContenidoPedidos(id_pedido=17, nombre='Pepperoni Clásica_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=20, nombre='Pepperoni Clásica_S', cantidad=3, descuento=0.32),
	ContenidoPedidos(id_pedido=21, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=22, nombre='Pepperoni Clásica_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=23, nombre='Pepperoni Clásica_L', cantidad=4, descuento=0.25),
	ContenidoPedidos(id_pedido=24, nombre='Pepperoni Clásica_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=25, nombre='Pepperoni Clásica_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=25, nombre='Pepperoni Clásica_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=27, nombre='Pepperoni Clásica_L', cantidad=4, descuento=0.14),
	ContenidoPedidos(id_pedido=28, nombre='Pepperoni Clásica_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=29, nombre='Pepperoni Clásica_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=29, nombre='Pepperoni Clásica_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=30, nombre='Pepperoni Clásica_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=32, nombre='Pepperoni Clásica_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=33, nombre='Pepperoni Clásica_M', cantidad=3, descuento=0.27),
	ContenidoPedidos(id_pedido=38, nombre='Pepperoni Clásica_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=38, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=39, nombre='Pepperoni Clásica_S', cantidad=2, descuento=0.25),
	ContenidoPedidos(id_pedido=48, nombre='Pepperoni Clásica_L', cantidad=5, descuento=0.3),
	ContenidoPedidos(id_pedido=49, nombre='Pepperoni Clásica_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=50, nombre='Pepperoni Clásica_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=52, nombre='Pepperoni Clásica_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=54, nombre='Pepperoni Clásica_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=54, nombre='Pepperoni Clásica_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=55, nombre='Pepperoni Clásica_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=55, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=56, nombre='Pepperoni Clásica_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=57, nombre='Pepperoni Clásica_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=59, nombre='Pepperoni Clásica_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=61, nombre='Pepperoni Clásica_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=66, nombre='Pepperoni Clásica_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=66, nombre='Pepperoni Clásica_L', cantidad=2, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_M_1 = [
    ContenidoPedidos(id_pedido=14, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=17, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=21, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=1, descuento=0.23),
	ContenidoPedidos(id_pedido=42, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=74, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=95, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=4, descuento=0.37),
	ContenidoPedidos(id_pedido=103, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=155, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=208, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=224, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=4, descuento=0.34),
	ContenidoPedidos(id_pedido=234, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=290, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=301, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=301, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=343, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=1, descuento=0.27),
	ContenidoPedidos(id_pedido=367, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=382, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=2, descuento=0.19),
	ContenidoPedidos(id_pedido=417, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=425, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=436, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=3, descuento=0.22),
	ContenidoPedidos(id_pedido=440, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=3, descuento=0.11),
	ContenidoPedidos(id_pedido=469, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=481, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=502, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=4, descuento=0.13),
	ContenidoPedidos(id_pedido=505, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=552, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=563, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=580, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=594, nombre='Asombroso Salado Sabroso con Cariño_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=627, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=628, nombre='Asombroso Salado Sabroso con Cariño_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=666, nombre='Asombroso Salado Sabroso con Cariño_M', cantidad=5, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_M_2 = [
    ContenidoPedidos(id_pedido=70, nombre='Fino Salado Increíble con Cautela_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=90, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=102, nombre='Fino Salado Increíble con Cautela_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=110, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=112, nombre='Fino Salado Increíble con Cautela_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=124, nombre='Fino Salado Increíble con Cautela_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=183, nombre='Fino Salado Increíble con Cautela_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=184, nombre='Fino Salado Increíble con Cautela_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=199, nombre='Fino Salado Increíble con Cautela_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=208, nombre='Fino Salado Increíble con Cautela_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=234, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=239, nombre='Fino Salado Increíble con Cautela_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=265, nombre='Fino Salado Increíble con Cautela_M', cantidad=1, descuento=0.19),
	ContenidoPedidos(id_pedido=271, nombre='Fino Salado Increíble con Cautela_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=293, nombre='Fino Salado Increíble con Cautela_M', cantidad=1, descuento=0.22),
	ContenidoPedidos(id_pedido=306, nombre='Fino Salado Increíble con Cautela_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=318, nombre='Fino Salado Increíble con Cautela_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=338, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=351, nombre='Fino Salado Increíble con Cautela_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=411, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=432, nombre='Fino Salado Increíble con Cautela_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=448, nombre='Fino Salado Increíble con Cautela_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=454, nombre='Fino Salado Increíble con Cautela_S', cantidad=4, descuento=0.18),
	ContenidoPedidos(id_pedido=475, nombre='Fino Salado Increíble con Cautela_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=479, nombre='Fino Salado Increíble con Cautela_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=486, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=513, nombre='Fino Salado Increíble con Cautela_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=539, nombre='Fino Salado Increíble con Cautela_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=542, nombre='Fino Salado Increíble con Cautela_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=575, nombre='Fino Salado Increíble con Cautela_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=585, nombre='Fino Salado Increíble con Cautela_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=592, nombre='Fino Salado Increíble con Cautela_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=595, nombre='Fino Salado Increíble con Cautela_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=596, nombre='Fino Salado Increíble con Cautela_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=604, nombre='Fino Salado Increíble con Cautela_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=612, nombre='Fino Salado Increíble con Cautela_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=623, nombre='Fino Salado Increíble con Cautela_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=626, nombre='Fino Salado Increíble con Cautela_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=637, nombre='Fino Salado Increíble con Cautela_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=639, nombre='Fino Salado Increíble con Cautela_M', cantidad=5, descuento=0.36)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_M_3 = [
    ContenidoPedidos(id_pedido=10, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=14, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=118, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=119, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=142, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=167, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=231, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=255, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=261, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=262, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=270, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=273, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=278, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=318, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=329, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=354, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.16),
	ContenidoPedidos(id_pedido=395, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=401, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=420, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=482, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=502, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=2, descuento=0.13),
	ContenidoPedidos(id_pedido=527, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=533, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=556, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=1, descuento=0.3),
	ContenidoPedidos(id_pedido=559, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=591, nombre='Perfecto Sabroso Perfecto con Estilo_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=594, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=611, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=3, descuento=0.2),
	ContenidoPedidos(id_pedido=617, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=636, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=3, descuento=0.4),
	ContenidoPedidos(id_pedido=636, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=1, descuento=0.4),
	ContenidoPedidos(id_pedido=640, nombre='Perfecto Sabroso Perfecto con Estilo_S', cantidad=2, descuento=0.33),
	ContenidoPedidos(id_pedido=650, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=5, descuento=0.24),
	ContenidoPedidos(id_pedido=654, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=685, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=3, descuento=0.35),
	ContenidoPedidos(id_pedido=687, nombre='Perfecto Sabroso Perfecto con Estilo_M', cantidad=5, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_L_1 = [
    ContenidoPedidos(id_pedido=147, nombre='Jugoso Suave Sublime con Arte_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=884, nombre='Jugoso Suave Sublime con Arte_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=1707, nombre='Jugoso Suave Sublime con Arte_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=5070, nombre='Jugoso Suave Sublime con Arte_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=5766, nombre='Jugoso Suave Sublime con Arte_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=6490, nombre='Jugoso Suave Sublime con Arte_L', cantidad=3, descuento=0.35),
	ContenidoPedidos(id_pedido=12385, nombre='Jugoso Suave Sublime con Arte_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=14365, nombre='Jugoso Suave Sublime con Arte_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=14856, nombre='Jugoso Suave Sublime con Arte_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=23426, nombre='Jugoso Suave Sublime con Arte_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=24863, nombre='Jugoso Suave Sublime con Arte_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=25149, nombre='Jugoso Suave Sublime con Arte_L', cantidad=4, descuento=0.16),
	ContenidoPedidos(id_pedido=26367, nombre='Jugoso Suave Sublime con Arte_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=28811, nombre='Jugoso Suave Sublime con Arte_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=37367, nombre='Jugoso Suave Sublime con Arte_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=38041, nombre='Jugoso Suave Sublime con Arte_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=38136, nombre='Jugoso Suave Sublime con Arte_S', cantidad=3, descuento=0.34),
	ContenidoPedidos(id_pedido=39192, nombre='Jugoso Suave Sublime con Arte_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=39407, nombre='Jugoso Suave Sublime con Arte_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=43240, nombre='Jugoso Suave Sublime con Arte_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=47750, nombre='Jugoso Suave Sublime con Arte_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=49078, nombre='Jugoso Suave Sublime con Arte_L', cantidad=3, descuento=0.3),
	ContenidoPedidos(id_pedido=49406, nombre='Jugoso Suave Sublime con Arte_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=52416, nombre='Jugoso Suave Sublime con Arte_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=55142, nombre='Jugoso Suave Sublime con Arte_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=58054, nombre='Jugoso Suave Sublime con Arte_S', cantidad=5, descuento=0.39),
	ContenidoPedidos(id_pedido=60842, nombre='Jugoso Suave Sublime con Arte_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=61323, nombre='Jugoso Suave Sublime con Arte_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=62005, nombre='Jugoso Suave Sublime con Arte_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=68597, nombre='Jugoso Suave Sublime con Arte_M', cantidad=3, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_L_2 = [
    ContenidoPedidos(id_pedido=2174, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=2383, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=3, descuento=0.12),
	ContenidoPedidos(id_pedido=2782, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=6073, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=8440, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=8916, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=3, descuento=0.31),
	ContenidoPedidos(id_pedido=10775, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=13445, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=16996, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=17882, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=17923, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=1, descuento=0.38),
	ContenidoPedidos(id_pedido=19196, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=5, descuento=0.24),
	ContenidoPedidos(id_pedido=19432, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=24900, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=26084, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=26227, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=29332, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=32188, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=33711, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=42912, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=43288, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=2, descuento=0.11),
	ContenidoPedidos(id_pedido=43735, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=44550, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=45340, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=45475, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=54579, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=54797, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=55297, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=5, descuento=0.34),
	ContenidoPedidos(id_pedido=56842, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=59751, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=61405, nombre='Dorado Delicioso Suave con Cariño_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=61481, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=62120, nombre='Dorado Delicioso Suave con Cariño_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=65582, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=3, descuento=0.35),
	ContenidoPedidos(id_pedido=68336, nombre='Dorado Delicioso Suave con Cariño_S', cantidad=1, descuento=0.38)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_L_3 = [
    ContenidoPedidos(id_pedido=803, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=1976, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=5346, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=7711, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=7999, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=8398, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=10567, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=3, descuento=0.22),
	ContenidoPedidos(id_pedido=10721, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=4, descuento=0.39),
	ContenidoPedidos(id_pedido=16116, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=21985, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=29316, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=29537, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=2, descuento=0.14),
	ContenidoPedidos(id_pedido=29602, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=31527, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=32720, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=4, descuento=0.39),
	ContenidoPedidos(id_pedido=35379, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=2, descuento=0.34),
	ContenidoPedidos(id_pedido=37932, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=5, descuento=0.24),
	ContenidoPedidos(id_pedido=39835, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=40729, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=42620, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=44082, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=44273, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=45666, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=45921, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=48979, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=1, descuento=0.29),
	ContenidoPedidos(id_pedido=50856, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=1, descuento=0.23),
	ContenidoPedidos(id_pedido=53694, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=57355, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=60265, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=2, descuento=0.38),
	ContenidoPedidos(id_pedido=64078, nombre='Tentador Vibrante Picante con Tradición_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=64130, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=66666, nombre='Tentador Vibrante Picante con Tradición_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=67864, nombre='Tentador Vibrante Picante con Tradición_S', cantidad=4, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_L_4 = [
    ContenidoPedidos(id_pedido=1253, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=5, descuento=0.3),
	ContenidoPedidos(id_pedido=4198, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=5095, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=6332, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=6536, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=6715, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=12217, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=12395, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=5, descuento=0.12),
	ContenidoPedidos(id_pedido=12890, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=14071, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=17536, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=3, descuento=0.28),
	ContenidoPedidos(id_pedido=17539, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=18110, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=18240, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=23158, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=30205, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=32396, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=36927, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=37957, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=39111, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=2, descuento=0.28),
	ContenidoPedidos(id_pedido=42029, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=2, descuento=0.14),
	ContenidoPedidos(id_pedido=47161, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=48037, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=49395, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=56029, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=57220, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=57580, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=1, descuento=0.2),
	ContenidoPedidos(id_pedido=58813, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=5, descuento=0.39),
	ContenidoPedidos(id_pedido=59363, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=59715, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=59799, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=63774, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=65849, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=2, descuento=0.28),
	ContenidoPedidos(id_pedido=66543, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=66829, nombre='Vibrante Sabroso Cremoso con Toque Divino_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=67161, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=69244, nombre='Vibrante Sabroso Cremoso con Toque Divino_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=69358, nombre='Vibrante Sabroso Cremoso con Toque Divino_M', cantidad=4, descuento=0.0)]

PEDIDOS_CON_AL_MENOS_ESTA_PIZZA_XL_1 = [
    ContenidoPedidos(id_pedido=0, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=5133, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=4, descuento=0.25),
	ContenidoPedidos(id_pedido=13892, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=37435, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=53265, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=58470, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=2, descuento=0.0),
	ContenidoPedidos(id_pedido=109653, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=125329, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=153032, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=5, descuento=0.25),
	ContenidoPedidos(id_pedido=224203, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=238567, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=3, descuento=0.36),
	ContenidoPedidos(id_pedido=266138, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=301612, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=318480, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=2, descuento=0.18),
	ContenidoPedidos(id_pedido=338938, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=382869, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=5, descuento=0.12),
	ContenidoPedidos(id_pedido=392075, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=412148, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=1, descuento=0.2),
	ContenidoPedidos(id_pedido=413127, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=445906, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=457702, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=474031, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=480208, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=485130, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=3, descuento=0.27),
	ContenidoPedidos(id_pedido=499933, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=501896, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=526013, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=547832, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=5, descuento=0.0),
	ContenidoPedidos(id_pedido=554313, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=556712, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=4, descuento=0.0),
	ContenidoPedidos(id_pedido=556986, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=2, descuento=0.1),
	ContenidoPedidos(id_pedido=569275, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=1, descuento=0.0),
	ContenidoPedidos(id_pedido=572700, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=5, descuento=0.16),
	ContenidoPedidos(id_pedido=627984, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=4, descuento=0.27),
	ContenidoPedidos(id_pedido=640748, nombre='Tierno Magnífico Radiante con Alegría_M', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=683704, nombre='Tierno Magnífico Radiante con Alegría_S', cantidad=3, descuento=0.0),
	ContenidoPedidos(id_pedido=692113, nombre='Tierno Magnífico Radiante con Alegría_L', cantidad=4, descuento=0.0)]